# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ppi',
                'doc_host': 'https://Dzeiberg.github.io',
                'git_url': 'https://github.com/Dzeiberg/ppi',
                'lib_path': 'ppi'},
  'syms': {'ppi.core': {'ppi.core.foo': ('core.html#foo', 'ppi/core.py')}}}